apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-rabbit
spec:
  selector:
    matchLabels:
      app: web-rabbit
  replicas: 1
  template:
    metadata:
      labels:
        app: web-rabbit
    spec:
      containers:
      - name: web-rabbit
        image: web.rabbit:latest
        imagePullPolicy: IfNotPresent #required to pull image from local docker registry, see https://minikube.sigs.k8s.io/docs/handbook/pushing/#1-pushing-directly-to-the-in-cluster-docker-daemon-docker-env
        ports:
        - containerPort: 15672
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: web-rabbit
spec:
  selector:
    app: web-rabbit
  ports:
    - name: manager
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: api
      protocol: TCP
      port: 5672
      targetPort: 5672